#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneVeritabani
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="kutuphane1927")]
	public partial class KutuphaneDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertdbKitaplar(dbKitaplar instance);
    partial void UpdatedbKitaplar(dbKitaplar instance);
    partial void DeletedbKitaplar(dbKitaplar instance);
    partial void InsertdbKitapTurleri(dbKitapTurleri instance);
    partial void UpdatedbKitapTurleri(dbKitapTurleri instance);
    partial void DeletedbKitapTurleri(dbKitapTurleri instance);
    #endregion
		
		public KutuphaneDataContext() : 
				base(global::KutuphaneVeritabani.Properties.Settings.Default.kutuphane1927ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KutuphaneDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KutuphaneDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KutuphaneDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KutuphaneDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dbKitaplar> dbKitaplars
		{
			get
			{
				return this.GetTable<dbKitaplar>();
			}
		}
		
		public System.Data.Linq.Table<dbKitapTurleri> dbKitapTurleris
		{
			get
			{
				return this.GetTable<dbKitapTurleri>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kitaplar")]
	public partial class dbKitaplar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _KitapAdi;
		
		private System.Nullable<int> _Turu;
		
		private string _Yazar;
		
		private System.Nullable<int> _SayfaSayisi;
		
		private System.Nullable<short> _BasimYili;
		
		private string _RafNo;
		
		private System.Nullable<short> _Adet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKitapAdiChanging(string value);
    partial void OnKitapAdiChanged();
    partial void OnTuruChanging(System.Nullable<int> value);
    partial void OnTuruChanged();
    partial void OnYazarChanging(string value);
    partial void OnYazarChanged();
    partial void OnSayfaSayisiChanging(System.Nullable<int> value);
    partial void OnSayfaSayisiChanged();
    partial void OnBasimYiliChanging(System.Nullable<short> value);
    partial void OnBasimYiliChanged();
    partial void OnRafNoChanging(string value);
    partial void OnRafNoChanged();
    partial void OnAdetChanging(System.Nullable<short> value);
    partial void OnAdetChanged();
    #endregion
		
		public dbKitaplar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KitapAdi", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string KitapAdi
		{
			get
			{
				return this._KitapAdi;
			}
			set
			{
				if ((this._KitapAdi != value))
				{
					this.OnKitapAdiChanging(value);
					this.SendPropertyChanging();
					this._KitapAdi = value;
					this.SendPropertyChanged("KitapAdi");
					this.OnKitapAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Turu", DbType="Int")]
		public System.Nullable<int> Turu
		{
			get
			{
				return this._Turu;
			}
			set
			{
				if ((this._Turu != value))
				{
					this.OnTuruChanging(value);
					this.SendPropertyChanging();
					this._Turu = value;
					this.SendPropertyChanged("Turu");
					this.OnTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yazar", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Yazar
		{
			get
			{
				return this._Yazar;
			}
			set
			{
				if ((this._Yazar != value))
				{
					this.OnYazarChanging(value);
					this.SendPropertyChanging();
					this._Yazar = value;
					this.SendPropertyChanged("Yazar");
					this.OnYazarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SayfaSayisi", DbType="Int")]
		public System.Nullable<int> SayfaSayisi
		{
			get
			{
				return this._SayfaSayisi;
			}
			set
			{
				if ((this._SayfaSayisi != value))
				{
					this.OnSayfaSayisiChanging(value);
					this.SendPropertyChanging();
					this._SayfaSayisi = value;
					this.SendPropertyChanged("SayfaSayisi");
					this.OnSayfaSayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasimYili", DbType="SmallInt")]
		public System.Nullable<short> BasimYili
		{
			get
			{
				return this._BasimYili;
			}
			set
			{
				if ((this._BasimYili != value))
				{
					this.OnBasimYiliChanging(value);
					this.SendPropertyChanging();
					this._BasimYili = value;
					this.SendPropertyChanged("BasimYili");
					this.OnBasimYiliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RafNo", DbType="VarChar(6)")]
		public string RafNo
		{
			get
			{
				return this._RafNo;
			}
			set
			{
				if ((this._RafNo != value))
				{
					this.OnRafNoChanging(value);
					this.SendPropertyChanging();
					this._RafNo = value;
					this.SendPropertyChanged("RafNo");
					this.OnRafNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adet", DbType="SmallInt")]
		public System.Nullable<short> Adet
		{
			get
			{
				return this._Adet;
			}
			set
			{
				if ((this._Adet != value))
				{
					this.OnAdetChanging(value);
					this.SendPropertyChanging();
					this._Adet = value;
					this.SendPropertyChanged("Adet");
					this.OnAdetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KitapTurleri")]
	public partial class dbKitapTurleri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _KitapTuru;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKitapTuruChanging(string value);
    partial void OnKitapTuruChanged();
    #endregion
		
		public dbKitapTurleri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KitapTuru", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string KitapTuru
		{
			get
			{
				return this._KitapTuru;
			}
			set
			{
				if ((this._KitapTuru != value))
				{
					this.OnKitapTuruChanging(value);
					this.SendPropertyChanging();
					this._KitapTuru = value;
					this.SendPropertyChanged("KitapTuru");
					this.OnKitapTuruChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
